// 中英双语字典 — 所有静态 UI 文案都走这里。
// 题目/逐字稿/范文保持英文（雅思考试是英文），只有界面 chrome 双语化。
// 键名用点分路径（如 "nav.bank"），命名按功能域分组。

export type Locale = "zh" | "en";

export const LOCALES: Locale[] = ["zh", "en"];

type Dict = Record<string, string>;

const zh: Dict = {
  // ===== 品牌 =====
  "brand.name": "雅思口语训练",
  "brand.tagline": "真题训练 · 答题框架 · 预测背诵",
  "brand.full": "雅思口语训练系统",

  // ===== 导航 =====
  "nav.bank": "题库",
  "nav.library": "素材本",
  "nav.progress": "成长档案",
  "nav.settings": "设置",
  "nav.practice": "练习",
  "nav.signIn": "登录",
  "nav.signOut": "退出",
  "nav.signUp": "注册",
  "nav.openMenu": "打开菜单",
  "nav.closeMenu": "关闭菜单",
  "nav.label": "主导航",

  // ===== 落地页 =====
  "home.hero.title": "练出你的雅思口语答题框架",
  "home.hero.subtitle":
    "基于历年真题开口练习，AI 自动提炼答题框架；临考用预测题按框架背诵，把会写变成能说。",
  "home.cta.start": "开始练习",
  "home.cta.progress": "查看训练进度",
  "home.cta.browse": "浏览题库",
  "home.step1.title": "① 真题训练",
  "home.step1.desc": "从历年真题题库选一道题，开口回答。实时识别并标记填充词、犹豫词、低分词。",
  "home.step2.title": "② 提炼框架",
  "home.step2.desc": "AI 基于你的回答自动提炼答题框架：结构、要点、高分表达，存入个人素材本。",
  "home.step3.title": "③ 预测背诵",
  "home.step3.desc": "临考切换到预测题库，用框架关键词提示卡背诵实践，考前内化输出。",

  // ===== 认证 =====
  "auth.signIn.title": "登录雅思口语训练",
  "auth.signUp.title": "创建账户",
  "auth.tab.signIn": "登录",
  "auth.tab.signUp": "注册",
  "auth.method.password": "密码登录",
  "auth.method.emailCode": "邮箱验证码",
  "auth.field.identifier": "邮箱或用户名",
  "auth.field.password": "密码",
  "auth.field.email": "邮箱",
  "auth.field.name": "你的名字",
  "auth.field.username": "用户名",
  "auth.field.code": "六位验证码",
  "auth.remember": "在此设备保持登录",
  "auth.submit.signIn": "登录",
  "auth.submit.signInBusy": "登录中…",
  "auth.submit.create": "创建账户",
  "auth.submit.createBusy": "创建中…",
  "auth.submit.sendCode": "发送登录验证码",
  "auth.submit.sendingCode": "发送中…",
  "auth.submit.verify": "验证并登录",
  "auth.submit.verifying": "验证中…",
  "auth.submit.verifyAndContinue": "验证并继续",
  "auth.codeSentTo": "验证码已发送至",
  "auth.useAnotherEmail": "使用其他邮箱",
  "auth.verifyEmail.title": "验证你的邮箱",
  "auth.resendCode": "重新发送验证码",
  "auth.create.subtitle": "注册一个账户，保存你的框架与练习记录",
  "auth.passwordHelp": "使用 8–128 位字符",
  "auth.otp.notice": "如果该邮箱有账户，六位验证码已发送",
  "auth.otp.notice2": "六位验证码已发送至你的邮箱",
  "auth.welcome": "欢迎使用雅思口语训练系统",
  "auth.terms": "注册即表示同意我们的使用条款与隐私政策",
  "auth.backHome": "返回首页",

  // ===== 题库 =====
  "bank.title": "雅思口语题库",
  "bank.subtitle": "选择一道题开始练习",
  "bank.part1": "Part 1",
  "bank.part2": "Part 2",
  "bank.part3": "Part 3",
  "bank.allParts": "全部",
  "bank.real": "历年真题",
  "bank.predicted": "预测题",
  "bank.year.all": "全部年份",
  "bank.topic.all": "全部话题",
  "bank.tier.year": "① 选择年份",
  "bank.tier.topic": "② 选择话题",
  "bank.tier.hintYear": "先选年份，再按年份查看对应话题",
  "bank.tier.hintTopic": "该年份下的话题",
  "bank.tier.selectYearFirst": "请先选择年份",
  "bank.practice": "开始练习",
  "bank.recite": "背记",
  "bank.modelAnswer": "看范文",
  "bank.needSignIn": "登录后可练习",
  "bank.empty": "该筛选条件下暂无题目",
  "bank.partLocked": "暂未开放",
  "bank.partLockedHint": "Part 2 / Part 3 暂未开放。当前 MVP 仅提供 Part 1 练习。",
  "bank.currentSelection": "当前选择",

  // ===== 练习 =====
  "practice.title": "口语练习",
  "practice.prepTime": "准备时间",
  "practice.prepDesc": "1 分钟准备你的回答",
  "practice.start": "开始录制",
  "practice.pause": "暂停",
  "practice.resume": "继续",
  "practice.stop": "结束",
  "practice.generateReport": "生成报告",
  "practice.speakHint": "点击开始，说出你的回答",
  "practice.recording": "正在录音…",
  "practice.paused": "已暂停",
  "practice.stat.fillers": "填充词",
  "practice.stat.hedges": "犹豫词",
  "practice.stat.vague": "低分词",
  "practice.stat.chinglish": "中式英语",
  "practice.stat.grammar": "语法",
  "practice.stat.density": "表达密度",
  "practice.stat.words": "词数",
  "practice.coach": "实时教练",
  "practice.coachEmpty": "AI 教练提示将显示在这里",
  "practice.framework": "答题框架",
  "practice.frameworkEmpty": "练习结束后可提取框架",
  "practice.saveFramework": "保存框架",
  "practice.report.title": "练习报告",
  "practice.report.generating": "正在生成报告…",
  "practice.report.failed": "报告生成失败，请稍后重试",
  "practice.report.close": "关闭",
  "practice.micUnsupported": "您的浏览器不支持语音识别，请使用 Chrome 或 Edge",
  "practice.micInsecure": "语音识别需要 HTTPS 安全连接。当前通过 http:// 访问，浏览器禁用了语音识别。请用 https:// 访问（或部署后使用）。",
  "practice.micPermission": "无法访问麦克风，请检查浏览器权限设置",
  "practice.micDenied": "麦克风权限已被拒绝。浏览器不会再次弹窗。请在浏览器地址栏左侧的🔒图标（或设置）中，将「麦克风」权限改为「允许」，然后点重试。",
  "practice.micUnavailable": "未检测到可用麦克风。请连接麦克风或在系统设置中启用它后重试。",
  "practice.micNetwork": "麦克风已获授权，但浏览器语音识别服务无法连接。请检查网络后重试。",
  "practice.micStartFailed": "无法启动语音识别。请刷新页面后重试。",
  "practice.micPrompt": "点击开始后，浏览器会弹出麦克风权限请求，请选择「允许」。",
  "practice.exit": "退出练习",
  "practice.speechCard.listening": "正在聆听…",
  "practice.speechCard.startHint": "点击下方按钮开始作答",
  "appShell.tagline": "基于历年真题 · 提炼框架 · 预测背诵",
  "library.stories": "故事素材",
  "library.storiesApply": "可复用于：{topics}",
  "bank.page.title": "雅思口语题库",
  "bank.page.subtitle": "历年真题训练 · 预测题背诵",

  // ===== AI 实时教官（逐题会话）=====
  "aiCoach.thinkHint": "思考后再开始回答。",
  "aiCoach.ready": "准备开始",
  "aiCoach.countdownHint": "点击开始录音后，倒计时才会启动。",
  "aiCoach.startRecording": "开始录音",
  "aiCoach.recording": "正在录音",
  "aiCoach.liveTranscriptHint": "稳定识别的内容会持续更新到实时转写中。",
  "aiCoach.waitingTranscript": "开始说你的回答…",
  "aiCoach.endAnswer": "结束回答",
  "aiCoach.autoStopHint": "倒计时至 00:00 时自动结束录音。",
  "aiCoach.saved": "这道题已保存",
  "aiCoach.transcript": "我的转录稿",
  "aiCoach.recommendedAnswer": "推荐回答",
  "aiCoach.vocabSummary": "标黄词汇汇总",
  "aiCoach.noVocab": "没有需要提升的词汇表达。",
  "aiCoach.grammarNotes": "语法与结构建议",
  "aiCoach.naturalRewrite": "自然改写",
  "aiCoach.generating": "生成中…",
  "aiCoach.nextQuestion": "下一题",
  "aiCoach.finishTopic": "完成话题练习",
  "aiCoach.topicSummary": "话题总结",
  "aiCoach.topicEstimate": "话题训练预估",
  "aiCoach.trainingOnly": "训练用途，非官方成绩",
  "aiCoach.summaryBasis": "预估判定依据",
  "aiCoach.nextFocus": "下次优先优化",
  "aiCoach.endSession": "结束本次练习",
  "aiCoach.nextTopic": "进入下一话题",
  "aiCoach.sessionSaved": "本次练习已保存",
  "aiCoach.topicsCompleted": "完成话题",
  "aiCoach.answersCount": "回答数量",
  "aiCoach.viewSummary": "查看话题总结",
  "aiCoach.otherTopics": "选择其他话题",
  "aiCoach.viewHistory": "查看历史训练",
  "aiCoach.sessionEstimate": "本次练习训练预估",
  "aiCoach.commonIssues": "跨话题共同问题",
  "aiCoach.startNewTopic": "开始新话题",
  "aiCoach.allTopicsCompleted": "已完成的全部话题",
  "aiCoach.targetedFollowUp": "针对性追问",
  "aiCoach.playRecording": "回放录音",
  "aiCoach.originalRecording": "原始录音",
  "aiCoach.back": "返回",
  "aiCoach.topicTransitionTitle": "下一话题确认",
  "aiCoach.topicCompleted": "已完成",
  "aiCoach.topicTransitionDesc": "你已完成这个话题的 {count} 道回答。确认后将开始下一个话题的第一问。",
  "aiCoach.nextTopicLabel": "下一话题",
  "aiCoach.startFromFirst": "Part 1 · 从第 1 问开始",
  "aiCoach.startTopic": "开始 {topic}",
  "aiCoach.returnToSummary": "返回话题总结",
  "aiCoach.sessionSummary": "已完成 {topics} 个话题、{answers} 道回答。以下结论只针对跨话题的共同表现。",
  "aiCoach.sessionEstimateNote": "基于已完成话题的回答得出，仅用于训练，不代表官方雅思成绩。",
  "aiCoach.viewTopicSummary": "查看话题总结",
  "aiCoach.noIssues": "暂无跨话题共同问题。",
  "aiCoach.stageTarget": "当前训练目标 {band}",
  "aiCoach.recommendedNote": "保留你的原意，按 {band} 分训练目标调整表达。",
  "aiCoach.secondsRemaining": "剩余 {seconds} 秒",

  // ===== 素材本 =====
  "library.title": "我的素材本",
  "library.subtitle": "按话题整理的答题框架",
  "library.empty": "还没有框架，先去题库练一道题吧",
  "library.edit": "编辑",
  "library.export": "导出",
  "library.delete": "删除",
  "library.deleteConfirm": "确定删除这个框架吗？",
  "library.structure": "结构",
  "library.keyPoints": "要点",
  "library.expressions": "高分表达",
  "library.intro": "导语",
  "library.save": "保存",
  "library.cancel": "取消",

  // ===== 背记 =====
  "recite.title": "背诵实践",
  "recite.hint": "看着关键词提示，自然地说出你的回答",
  "recite.reveal": "显示提示词",
  "recite.hide": "隐藏提示词",
  "recite.compare": "对比范文",
  "recite.predicted": "预测题",
  "recite.cues": "要点提示",
  "recite.expressions": "高分表达",
  "recite.noFramework": "还没有这个话题的框架，先去题库练一道题生成框架吧。",

  // ===== 五层目标级回答 =====
  "fiveTier.title": "目标级回答",
  "fiveTier.desc": "根据你的当前水平，生成从原文到目标分的升级回答",
  "fiveTier.generate": "生成目标级回答",
  "fiveTier.generating": "生成中…",
  "fiveTier.band": "当前 {current} → 目标 {target}",
  "fiveTier.steps": "⑤ 提升步骤",
  "fiveTier.tier.original": "① 你的原文",
  "fiveTier.tier.structured": "② 结构化",
  "fiveTier.tier.improvable": "③ 可改进版",
  "fiveTier.tier.target": "④ 目标级回答",

  // ===== 练习会话（实时面板）=====
  "practice.liveStats": "实时统计",
  "practice.coachTip.filler": "「{word}」— 填充词，试试停顿",
  "practice.coachTip.hedge": "「{word}」— 犹豫词，直接说",
  "practice.coachTip.vague": "「{word}」→ {suggestion}",
  "practice.coachTip.vague.default": "换高分词",
  "practice.coachTip.chinglish": "「{word}」— 中式英语，用 {suggestion}",
  "practice.coachTip.chinglish.default": "更地道的说法",
  "practice.coachTip.grammar": "「{word}」— {suggestion}",
  "practice.coachTip.grammar.default": "语法错误",
  "practice.error.noRecording": "请先录制并说一段回答，再生成目标级回答",
  "practice.error.generate": "生成失败，请稍后重试",
  "practice.framework.extracting": "正在提取…",
  "practice.framework.extractingLong": "正在提取框架…",
  "practice.framework.error": "提取失败，请重试",
  "practice.framework.saved": "已保存到素材本 ✓",
  "practice.framework.saving": "保存中…",
  "practice.framework.structure": "结构",
  "practice.framework.keyPoints": "要点",
  "practice.framework.stories": "故事素材",
  "practice.framework.storiesApply": "可复用于 {topics}",
  "practice.similar.title": "相似题",
  "practice.similar.empty": "暂无相似题，尝试练习后提炼框架",
  "practice.assessment.overall": "当前综合水平",
  "practice.assessment.estimate": "预估分",
  "practice.assessment.target": "目标分",

  // ===== 设置 =====
  "settings.title": "设置",
  "settings.language": "界面语言",
  "settings.language.zh": "中文",
  "settings.language.en": "English",
  "settings.asr": "语言模式",
  "settings.asr.desc": "同时控制语音识别与实时词级分析（中文/英文）",
  "settings.account": "账户",
  "settings.account.email": "邮箱",
  "settings.account.username": "用户名",
  "settings.signOut": "退出登录",
  "settings.llm": "AI 服务",
  "settings.llm.configured": "已配置",
  "settings.llm.notConfigured": "未配置",
  "settings.llm.provider": "服务商",

  // ===== 成长档案 =====
  "progress.title": "成长档案",
  "progress.subtitle": "你的能力水平、练习历史与提分趋势",
  "progress.profile": "能力档案",
  "progress.profile.empty": "还没有能力档案。完成一次诊断，AI 会评估你的当前水平。",
  "progress.profile.goDiagnostic": "去诊断",
  "progress.overall": "当前综合水平",
  "progress.target": "目标分数",
  "progress.targetSet": "目标分数",
  "progress.updatedAt": "最近评估",
  "progress.dimensions": "四维能力",
  "progress.mainIssues": "当前最主要的问题",
  "progress.stagePath": "通往目标的阶段路径",
  "progress.history": "练习历史",
  "progress.history.empty": "还没有练习记录，去题库练一道题吧。",
  "progress.history.goPractice": "去练习",
  "progress.history.count": "共 {count} 次",
  "progress.trend": "综合水平趋势",
  "progress.trend.empty": "完成 2 次以上带评估的练习后，这里会显示趋势图。",
  "progress.mode.train": "训练",
  "progress.mode.recite": "背记",
  "progress.band": "Band",
  "progress.noBand": "未评估",
  "progress.session.words": "{n} 词",
  "progress.session.duration": "{m} 分 {s} 秒",
  "progress.session.report": "查看报告",
  "progress.table.question": "题目",
  "progress.table.band": "Band",
  "progress.table.time": "时长",
  "progress.table.date": "时间",
  "progress.legend.train": "训练",
  "progress.legend.recite": "背记",

  // ===== 通用 =====
  "common.loading": "加载中…",
  "common.back": "返回",
  "common.close": "关闭",
  "common.play": "播放",
  "common.pause": "暂停",
  "common.cancel": "取消",
  "common.confirm": "确认",
  "common.error": "出错了",
  "common.retry": "重试",
  "common.minutes": "分钟",
  "common.seconds": "秒",
  "common.word": "词",
  "common.words": "词",
  "common.mode.train": "训练",
  "common.mode.recite": "背记",

  // ===== 诊断（onboarding）=====
  "onboarding.error.minAnswers": "请至少完成 2 道题的回答",
  "onboarding.error.diagnostic": "诊断失败，请稍后重试",
  "onboarding.step1.title": "建立你的起点",
  "onboarding.step1.desc": "先设定目标分数，再通过简短诊断了解当前水平",
  "onboarding.step1.targetLabel": "你的雅思口语目标分数",
  "onboarding.step1.targetHint": "目标分数决定 AI 反馈的详细程度、推荐词汇难度和目标级回答的水平",
  "onboarding.step1.start": "开始诊断",
  "onboarding.v1.packageTitle": "诊断包含 8 道标准题",
  "onboarding.v1.packageDesc": "两个最新标准话题 × 4 题，共 8 道有效回答。完成后生成训练用途能力档案、当前训练目标和阶段路径；诊断进度会自动保留，随时可继续。",
  "onboarding.answer.answered": "已答 {done}",
  "onboarding.answer.questionIndex": "第 {index} 题 · 无需准备，自然作答",
  "onboarding.answer.assessing": "正在评估…",
  "onboarding.answer.finish": "完成诊断",
  "onboarding.answer.next": "下一题",
  "onboarding.result.title": "你的能力档案",
  "onboarding.result.desc": "这是训练用途的预估水平，不是官方成绩",
  "onboarding.result.current": "当前水平",
  "onboarding.result.target": "目标分数",
  "onboarding.result.dimensions": "四维能力",
  "onboarding.result.issues": "当前最主要的问题",
  "onboarding.result.stagePath": "通往 {target} 的阶段路径",
  "onboarding.result.startPractice": "开始练习",

  // ===== V1 练习（熟悉话题 / 标准话题）=====
  "v1.home.title": "开始练习",
  "v1.home.desc": "选择一种练习方式：两种模式独立，题目与历史互不混淆",
  "v1.home.familiar": "熟悉话题",
  "v1.home.familiar.desc": "工作/学习、家乡、住所；每次选一个大类，按固定顺序完成 3-4 题",
  "v1.home.familiar.badge": "不评分 · 不进入诊断",
  "v1.home.standard": "标准话题",
  "v1.home.standard.desc": "先选年份或最新话题，再按 Part → 话题 进入已发布标准题组",
  "v1.home.standard.badge": "标准题 · 可进入诊断",
  "v1.familiar.title": "熟悉话题 · 选择大类",
  "v1.familiar.desc": "每次选择一个熟悉话题大类，按固定顺序完成练习",
  "v1.familiar.questions": "{count} 道题",
  "v1.familiar.trainingNote": "本模式只提供训练用途反馈：不显示分数、不生成能力档案、不影响标准题诊断",
  "v1.standard.title": "标准话题",
  "v1.standard.scopeStep": "第一步 · 选择年份或最新话题",
  "v1.standard.latest": "最新话题",
  "v1.standard.latestDesc": "最新已发布标准题组",
  "v1.standard.partStep": "第二步 · 选择 Part",
  "v1.standard.partLocked": "暂未开放",
  "v1.standard.topicStep": "第三步 · 选择标准话题",
  "v1.standard.topicDesc": "每个话题 {count} 道已发布标准题，顺序固定",
  "v1.standard.empty": "该范围暂无已发布标准话题",
  "v1.standard.source": "来源 {source}",
  "v1.session.questionMeta": "第 {index} 题 · 共 {total} 题",
  "v1.session.ready": "准备开始",
  "v1.session.thinkHint": "思考后开始录音，单次最长 30 秒",
  "v1.session.startRecording": "开始录音",
  "v1.session.recording": "正在录音",
  "v1.session.endAnswer": "结束回答",
  "v1.session.autoStop": "30 秒后自动停止",
  "v1.session.waitingTranscript": "等待识别…",
  "v1.session.liveHint": "实时转写 · 黄色标记为可提升的词汇表达",
  "v1.session.confirmTitle": "确认你的回答",
  "v1.session.confirmDesc": "可编辑转写、重录或手动补写；确认非空后保存并生成反馈",
  "v1.session.confirmAndSave": "确认并保存",
  "v1.session.retry": "重录",
  "v1.session.skip": "跳过此题",
  "v1.session.manualHint": "识别为空？可直接在下方输入你的回答",
  "v1.session.saving": "正在保存回答…",
  "v1.session.feedbackTitle": "表达反馈",
  "v1.session.vocab": "词汇建议",
  "v1.session.vocabEmpty": "本次回答暂无词汇建议",
  "v1.session.rewrite": "自然改写（保留原意）",
  "v1.session.rewriteGenerating": "正在生成改写…",
  "v1.session.degraded": "回答已保存，反馈暂不可用",
  "v1.session.degradedRetry": "重试生成反馈",
  "v1.session.saved": "回答已保存",
  "v1.session.stageTarget": "按 {band} 分训练目标生成",
  "v1.session.next": "下一题",
  "v1.session.finish": "完成练习",
  "v1.session.summaryFamiliar.title": "练习总结",
  "v1.session.summaryFamiliar.desc": "训练用途反馈，非官方成绩；本模式不生成评分与诊断",
  "v1.session.summaryStandard.title": "话题训练预估",
  "v1.session.summaryStandard.note": "训练用途预估，非官方成绩",
  "v1.session.summary.basis": "判定依据",
  "v1.session.summary.nextFocus": "下次优化点",
  "v1.session.summary.answers": "完成 {count} 道题",
  "v1.session.summary.backHome": "返回练习首页",
  "v1.session.summary.viewHistory": "查看历史",
  "v1.session.summary.repractice": "再练一次",
  "v1.session.summary.unavailable": "总结暂不可用，可稍后重试",
  "v1.session.summary.generating": "正在生成总结…",
  "v1.session.micError": "麦克风不可用：{message}",
  "v1.session.aria.timer": "剩余 {seconds} 秒",
  "v1.session.loadError": "练习会话加载失败",

  // ===== V1 历史（FR-010）=====
  "v1.history.title": "日常练习",
  "v1.history.empty": "还没有日常练习记录，去练习页开始第一次开口吧",
  "v1.history.review": "复盘",
  "v1.history.delete": "删除",
  "v1.history.confirmDelete": "确认删除这条练习记录？",
  "v1.history.status.completed": "已完成",
  "v1.history.status.in_progress": "进行中",
  "v1.history.answers": "{done}/{total} 题",
  "v1.history.reviewTitle": "练习复盘",
  "v1.history.estimate": "训练预估 {band}",
  "v1.history.reviewQuestion": "第 {index} 题",
  "v1.history.reviewSkipped": "已跳过",

  // ===== V1 诊断（FR-009）=====
  "v1.diag.title": "诊断完成",
  "v1.diag.desc": "训练用途评估，非官方成绩",
  "v1.diag.current": "当前水平",
  "v1.diag.target": "最终目标",
  "v1.diag.stage": "当前训练目标",
  "v1.diag.dimensions": "四维能力",
  "v1.diag.notAssessed": "未评估",
  "v1.diag.notes": "证据说明",
  "v1.diag.stagePlan": "阶段路径",
  "v1.diag.startPractice": "开始练习",
  "v1.diag.viewProgress": "查看成长档案",
};

const en: Dict = {
  "brand.name": "IELTS Speaking",
  "brand.tagline": "Real questions · Frameworks · Predicted reciting",
  "brand.full": "IELTS Speaking Trainer",

  "nav.bank": "Question Bank",
  "nav.library": "My Frameworks",
  "nav.progress": "Progress",
  "nav.settings": "Settings",
  "nav.practice": "Practice",
  "nav.signIn": "Sign in",
  "nav.signOut": "Sign out",
  "nav.signUp": "Sign up",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "nav.label": "Main navigation",

  "home.hero.title": "Build your IELTS speaking framework",
  "home.hero.subtitle":
    "Practice on real past-exam questions, let AI extract a reusable answer framework, then recite on predicted questions before your test.",
  "home.cta.start": "Start practicing",
  "home.cta.progress": "View training progress",
  "home.cta.browse": "Browse questions",
  "home.step1.title": "① Train on real questions",
  "home.step1.desc": "Pick a question from the past-exam bank and answer it out loud. Fillers, hesitations and low-band words are marked in real time.",
  "home.step2.title": "② Extract a framework",
  "home.step2.desc": "AI distills your answer into a framework: structure, key points and high-band expressions, saved to your library.",
  "home.step3.title": "③ Recite on predicted questions",
  "home.step3.desc": "Switch to the predicted bank before your test and recite from keyword cue cards to internalize your frameworks.",

  "auth.signIn.title": "Sign in to IELTS Speaking",
  "auth.signUp.title": "Create your account",
  "auth.tab.signIn": "Sign in",
  "auth.tab.signUp": "Sign up",
  "auth.method.password": "Password",
  "auth.method.emailCode": "Email code",
  "auth.field.identifier": "Email or username",
  "auth.field.password": "Password",
  "auth.field.email": "Email",
  "auth.field.name": "Your name",
  "auth.field.username": "Username",
  "auth.field.code": "Six-digit code",
  "auth.remember": "Keep me signed in on this device",
  "auth.submit.signIn": "Sign in",
  "auth.submit.signInBusy": "Signing in…",
  "auth.submit.create": "Create account",
  "auth.submit.createBusy": "Creating…",
  "auth.submit.sendCode": "Send sign-in code",
  "auth.submit.sendingCode": "Sending…",
  "auth.submit.verify": "Verify and sign in",
  "auth.submit.verifying": "Verifying…",
  "auth.submit.verifyAndContinue": "Verify and continue",
  "auth.codeSentTo": "Code sent to",
  "auth.useAnotherEmail": "Use another email",
  "auth.verifyEmail.title": "Verify your email",
  "auth.resendCode": "Resend verification code",
  "auth.create.subtitle": "Create an account to save your frameworks and practice history",
  "auth.passwordHelp": "Use 8–128 characters",
  "auth.otp.notice": "If this email belongs to an account, a six-digit code is on its way.",
  "auth.otp.notice2": "A six-digit verification code is on its way.",
  "auth.welcome": "Welcome to IELTS Speaking Trainer",
  "auth.terms": "By signing up you agree to our Terms of Service and Privacy Policy",
  "auth.backHome": "Back to home",

  "bank.title": "IELTS Speaking Question Bank",
  "bank.subtitle": "Pick a question to start practicing",
  "bank.part1": "Part 1",
  "bank.part2": "Part 2",
  "bank.part3": "Part 3",
  "bank.allParts": "All",
  "bank.real": "Real questions",
  "bank.predicted": "Predicted",
  "bank.year.all": "All years",
  "bank.topic.all": "All topics",
  "bank.tier.year": "① Pick a year",
  "bank.tier.topic": "② Pick a topic",
  "bank.tier.hintYear": "Choose a year first, then its topics",
  "bank.tier.hintTopic": "Topics in this year",
  "bank.tier.selectYearFirst": "Pick a year first",
  "bank.practice": "Start practice",
  "bank.recite": "Recite",
  "bank.modelAnswer": "Model answer",
  "bank.needSignIn": "Sign in to practice",
  "bank.empty": "No questions match this filter",
  "bank.partLocked": "Coming soon",
  "bank.partLockedHint": "Part 2 / Part 3 are not available yet. The MVP currently offers Part 1 practice only.",
  "bank.currentSelection": "Current selection",

  "practice.title": "Speaking practice",
  "practice.prepTime": "Preparation",
  "practice.prepDesc": "Prepare your answer for 1 minute",
  "practice.start": "Start recording",
  "practice.pause": "Pause",
  "practice.resume": "Resume",
  "practice.stop": "Stop",
  "practice.generateReport": "Generate report",
  "practice.speakHint": "Click start and speak your answer",
  "practice.recording": "Recording…",
  "practice.paused": "Paused",
  "practice.stat.fillers": "Fillers",
  "practice.stat.hedges": "Hesitations",
  "practice.stat.vague": "Low-band words",
  "practice.stat.chinglish": "Chinglish",
  "practice.stat.grammar": "Grammar",
  "practice.stat.density": "Density",
  "practice.stat.words": "Words",
  "practice.coach": "AI Coach",
  "practice.coachEmpty": "AI coaching tips will appear here",
  "practice.framework": "Answer framework",
  "practice.frameworkEmpty": "Extract a framework after you finish",
  "practice.saveFramework": "Save framework",
  "practice.report.title": "Practice report",
  "practice.report.generating": "Generating report…",
  "practice.report.failed": "Failed to generate report. Try again.",
  "practice.report.close": "Close",
  "practice.micUnsupported": "Your browser does not support speech recognition. Use Chrome or Edge.",
  "practice.micInsecure": "Speech recognition requires a secure (HTTPS) connection. Accessing via http:// disables it. Please use an https:// URL (or deploy the site).",
  "practice.micPermission": "Cannot access the microphone. Check your browser permissions.",
  "practice.micDenied": "Microphone permission is blocked. The browser will not ask again. Click the 🔒 icon next to the address bar (or browser settings), change \"Microphone\" to \"Allow\", then retry.",
  "practice.micUnavailable": "No microphone was found. Connect or enable a microphone in your system settings, then retry.",
  "practice.micNetwork": "The microphone is allowed, but the browser's speech recognition service could not connect. Check your network and retry.",
  "practice.micStartFailed": "Speech recognition could not start. Refresh the page and retry.",
  "practice.micPrompt": "After clicking start, the browser will ask for microphone access. Please choose \"Allow\".",
  "practice.exit": "Exit practice",
  "practice.speechCard.listening": "Listening…",
  "practice.speechCard.startHint": "Click the button below to start answering",
  "appShell.tagline": "Real questions · Frameworks · Predicted reciting",
  "library.stories": "Story materials",
  "library.storiesApply": "Reusable for: {topics}",
  "bank.page.title": "IELTS Speaking Question Bank",
  "bank.page.subtitle": "Train on real questions · Recite predicted ones",

  // ===== AI real-time coach (turn-by-turn session) =====
  "aiCoach.thinkHint": "Take a moment to think before you answer.",
  "aiCoach.ready": "Ready to start",
  "aiCoach.countdownHint": "The countdown starts once you begin recording.",
  "aiCoach.startRecording": "Start recording",
  "aiCoach.recording": "Recording",
  "aiCoach.liveTranscriptHint": "Stable speech is continuously added to the live transcript.",
  "aiCoach.waitingTranscript": "Start speaking…",
  "aiCoach.endAnswer": "End answer",
  "aiCoach.autoStopHint": "Recording stops automatically at 00:00.",
  "aiCoach.saved": "This answer is saved",
  "aiCoach.transcript": "My transcript",
  "aiCoach.recommendedAnswer": "Recommended answer",
  "aiCoach.vocabSummary": "Highlighted vocabulary",
  "aiCoach.noVocab": "No vocabulary to improve in this answer.",
  "aiCoach.grammarNotes": "Grammar & structure",
  "aiCoach.naturalRewrite": "Natural rewrite",
  "aiCoach.generating": "Generating…",
  "aiCoach.nextQuestion": "Next question",
  "aiCoach.finishTopic": "Finish topic",
  "aiCoach.topicSummary": "Topic summary",
  "aiCoach.topicEstimate": "Topic estimate",
  "aiCoach.trainingOnly": "For training only, not an official score",
  "aiCoach.summaryBasis": "Estimate basis",
  "aiCoach.nextFocus": "Next focus",
  "aiCoach.endSession": "End this session",
  "aiCoach.nextTopic": "Next topic",
  "aiCoach.sessionSaved": "This practice is saved",
  "aiCoach.topicsCompleted": "Topics completed",
  "aiCoach.answersCount": "Answers",
  "aiCoach.viewSummary": "View topic summary",
  "aiCoach.otherTopics": "Choose another topic",
  "aiCoach.viewHistory": "View history",
  "aiCoach.sessionEstimate": "Session estimate",
  "aiCoach.commonIssues": "Common issues across topics",
  "aiCoach.startNewTopic": "Start a new topic",
  "aiCoach.allTopicsCompleted": "All completed topics",
  "aiCoach.targetedFollowUp": "Targeted follow-up",
  "aiCoach.playRecording": "Play recording",
  "aiCoach.originalRecording": "Original recording",
  "aiCoach.back": "Back",
  "aiCoach.topicTransitionTitle": "Next topic",
  "aiCoach.topicCompleted": "completed",
  "aiCoach.topicTransitionDesc": "You have finished {count} answers in this topic. Confirming will start the first question of the next topic.",
  "aiCoach.nextTopicLabel": "Next topic",
  "aiCoach.startFromFirst": "Part 1 · Starting from question 1",
  "aiCoach.startTopic": "Start {topic}",
  "aiCoach.returnToSummary": "Back to topic summary",
  "aiCoach.sessionSummary": "Completed {topics} topics, {answers} answers. The conclusions below cover your common performance across topics.",
  "aiCoach.sessionEstimateNote": "Based on your answers across these topics. For training only, not an official IELTS score.",
  "aiCoach.viewTopicSummary": "View topic summary",
  "aiCoach.noIssues": "No common issues across topics yet.",
  "aiCoach.stageTarget": "Training target {band}",
  "aiCoach.recommendedNote": "Keeps your meaning, adjusted to a {band} training target.",
  "aiCoach.secondsRemaining": "{seconds} seconds remaining",

  "library.title": "My Frameworks",
  "library.subtitle": "Answer frameworks organized by topic",
  "library.empty": "No frameworks yet. Practice a question to build one.",
  "library.edit": "Edit",
  "library.export": "Export",
  "library.delete": "Delete",
  "library.deleteConfirm": "Delete this framework?",
  "library.structure": "Structure",
  "library.keyPoints": "Key points",
  "library.expressions": "High-band expressions",
  "library.intro": "Intro",
  "library.save": "Save",
  "library.cancel": "Cancel",

  "recite.title": "Recite practice",
  "recite.hint": "Look at the keyword cues and speak your answer naturally",
  "recite.reveal": "Reveal cues",
  "recite.hide": "Hide cues",
  "recite.compare": "Compare with model answer",
  "recite.predicted": "Predicted",
  "recite.cues": "Key cues",
  "recite.expressions": "High-band expressions",
  "recite.noFramework": "No framework for this topic yet. Practice a question in the bank to build one.",

  // ===== Five-tier answer =====
  "fiveTier.title": "Target-band answer",
  "fiveTier.desc": "Based on your current level, generates an upgraded answer from your original to the target band",
  "fiveTier.generate": "Generate target-band answer",
  "fiveTier.generating": "Generating…",
  "fiveTier.band": "Current {current} → Target {target}",
  "fiveTier.steps": "⑤ Improvement steps",
  "fiveTier.tier.original": "① Your original",
  "fiveTier.tier.structured": "② Structured",
  "fiveTier.tier.improvable": "③ Improvable version",
  "fiveTier.tier.target": "④ Target-band answer",

  // ===== Practice session (live panels) =====
  "practice.liveStats": "Live stats",
  "practice.coachTip.filler": "“{word}” — filler, try a pause",
  "practice.coachTip.hedge": "“{word}” — hesitation, just say it",
  "practice.coachTip.vague": "“{word}” → {suggestion}",
  "practice.coachTip.vague.default": "use a higher-band word",
  "practice.coachTip.chinglish": "“{word}” — Chinglish, use {suggestion}",
  "practice.coachTip.chinglish.default": "a more natural phrase",
  "practice.coachTip.grammar": "“{word}” — {suggestion}",
  "practice.coachTip.grammar.default": "grammar issue",
  "practice.error.noRecording": "Record and say an answer first, then generate the target-band answer",
  "practice.error.generate": "Generation failed. Please try again.",
  "practice.framework.extracting": "Extracting…",
  "practice.framework.extractingLong": "Extracting framework…",
  "practice.framework.error": "Extraction failed. Try again.",
  "practice.framework.saved": "Saved to library ✓",
  "practice.framework.saving": "Saving…",
  "practice.framework.structure": "Structure",
  "practice.framework.keyPoints": "Key points",
  "practice.framework.stories": "Story materials",
  "practice.framework.storiesApply": "Reusable for {topics}",
  "practice.similar.title": "Similar questions",
  "practice.similar.empty": "No similar questions yet. Practice one to extract a framework.",
  "practice.assessment.overall": "Current overall",
  "practice.assessment.estimate": "Estimate",
  "practice.assessment.target": "Target",

  "settings.title": "Settings",
  "settings.language": "Interface language",
  "settings.language.zh": "中文",
  "settings.language.en": "English",
  "settings.asr": "Language mode",
  "settings.asr.desc": "Controls both speech recognition and real-time word analysis (Chinese / English)",
  "settings.account": "Account",
  "settings.account.email": "Email",
  "settings.account.username": "Username",
  "settings.signOut": "Sign out",
  "settings.llm": "AI service",
  "settings.llm.configured": "Configured",
  "settings.llm.notConfigured": "Not configured",
  "settings.llm.provider": "Provider",

  // ===== Progress =====
  "progress.title": "Progress",
  "progress.subtitle": "Your ability, practice history and band trend",
  "progress.profile": "Ability profile",
  "progress.profile.empty": "No ability profile yet. Complete a diagnostic and AI will estimate your current level.",
  "progress.profile.goDiagnostic": "Go diagnose",
  "progress.overall": "Current overall",
  "progress.target": "Target band",
  "progress.targetSet": "Target band",
  "progress.updatedAt": "Last assessed",
  "progress.dimensions": "Four dimensions",
  "progress.mainIssues": "Main issues",
  "progress.stagePath": "Path to target",
  "progress.history": "Practice history",
  "progress.history.empty": "No practice yet. Pick a question and start speaking.",
  "progress.history.goPractice": "Start practicing",
  "progress.history.count": "{count} sessions",
  "progress.trend": "Overall band trend",
  "progress.trend.empty": "The trend chart appears after 2+ assessed practices.",
  "progress.mode.train": "Train",
  "progress.mode.recite": "Recite",
  "progress.band": "Band",
  "progress.noBand": "Not assessed",
  "progress.session.words": "{n} words",
  "progress.session.duration": "{m} min {s} sec",
  "progress.session.report": "View report",
  "progress.table.question": "Question",
  "progress.table.band": "Band",
  "progress.table.time": "Duration",
  "progress.table.date": "Date",
  "progress.legend.train": "Train",
  "progress.legend.recite": "Recite",

  "common.loading": "Loading…",
  "common.back": "Back",
  "common.close": "Close",
  "common.play": "Play",
  "common.pause": "Pause",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.error": "Something went wrong",
  "common.retry": "Retry",
  "common.minutes": "min",
  "common.seconds": "s",
  "common.word": "word",
  "common.words": "words",
  "common.mode.train": "Train",
  "common.mode.recite": "Recite",

  // ===== Onboarding =====
  "onboarding.error.minAnswers": "Answer at least 2 questions first",
  "onboarding.error.diagnostic": "Diagnostic failed. Please try again.",
  "onboarding.step1.title": "Build your starting point",
  "onboarding.step1.desc": "Set a target band, then a short diagnostic will estimate your current level",
  "onboarding.step1.targetLabel": "Your target IELTS speaking band",
  "onboarding.step1.targetHint": "The target band controls how detailed the AI feedback is, the suggested vocabulary level, and the target-band sample answer",
  "onboarding.step1.start": "Start diagnostic",
  "onboarding.v1.packageTitle": "The diagnostic contains 8 standard questions",
  "onboarding.v1.packageDesc": "Two latest standard topics × 4 questions, 8 valid answers in total. You get a training ability profile, current training target and stage path on completion; progress is saved and you can continue anytime.",
  "onboarding.answer.answered": "{done} answered",
  "onboarding.answer.questionIndex": "Question {index} · answer naturally, no prep",
  "onboarding.answer.assessing": "Assessing…",
  "onboarding.answer.finish": "Finish diagnostic",
  "onboarding.answer.next": "Next",
  "onboarding.result.title": "Your ability profile",
  "onboarding.result.desc": "This is an estimated level for training, not an official score",
  "onboarding.result.current": "Current level",
  "onboarding.result.target": "Target band",
  "onboarding.result.dimensions": "Four dimensions",
  "onboarding.result.issues": "Current main issues",
  "onboarding.result.stagePath": "Path to {target}",
  "onboarding.result.startPractice": "Start practicing",

  // ===== V1 Practice (familiar / standard topics) =====
  "v1.home.title": "Start practicing",
  "v1.home.desc": "Choose a practice mode — the two modes are independent, questions and history never mix",
  "v1.home.familiar": "Familiar topics",
  "v1.home.familiar.desc": "Work & study, hometown, residence. Pick one category and answer 3-4 fixed questions in order",
  "v1.home.familiar.badge": "No band · no diagnostic",
  "v1.home.standard": "Standard topics",
  "v1.home.standard.desc": "Pick a year or the latest topics, then Part → topic to enter a published standard question set",
  "v1.home.standard.badge": "Standard questions · diagnostic eligible",
  "v1.familiar.title": "Familiar topics · pick a category",
  "v1.familiar.desc": "Pick one familiar topic category and answer the fixed questions in order",
  "v1.familiar.questions": "{count} questions",
  "v1.familiar.trainingNote": "This mode gives training feedback only: no band, no ability profile, no effect on the standard-topic diagnostic",
  "v1.standard.title": "Standard topics",
  "v1.standard.scopeStep": "Step 1 · pick a year or the latest topics",
  "v1.standard.latest": "Latest topics",
  "v1.standard.latestDesc": "Most recently published standard question sets",
  "v1.standard.partStep": "Step 2 · pick a Part",
  "v1.standard.partLocked": "Not available yet",
  "v1.standard.topicStep": "Step 3 · pick a standard topic",
  "v1.standard.topicDesc": "{count} published standard questions per topic, fixed order",
  "v1.standard.empty": "No published standard topics in this range",
  "v1.standard.source": "Source {source}",
  "v1.session.questionMeta": "Question {index} of {total}",
  "v1.session.ready": "Get ready",
  "v1.session.thinkHint": "Think first, then record. Each answer is up to 30 seconds",
  "v1.session.startRecording": "Start recording",
  "v1.session.recording": "Recording",
  "v1.session.endAnswer": "End answer",
  "v1.session.autoStop": "Auto-stops after 30 seconds",
  "v1.session.waitingTranscript": "Waiting for speech…",
  "v1.session.liveHint": "Live transcript · yellow marks are vocabulary you can improve",
  "v1.session.confirmTitle": "Confirm your answer",
  "v1.session.confirmDesc": "Edit the transcript, re-record or type it in. It is saved and feedback is generated only after you confirm",
  "v1.session.confirmAndSave": "Confirm & save",
  "v1.session.retry": "Re-record",
  "v1.session.skip": "Skip question",
  "v1.session.manualHint": "Nothing recognized? Type your answer below",
  "v1.session.saving": "Saving your answer…",
  "v1.session.feedbackTitle": "Expression feedback",
  "v1.session.vocab": "Vocabulary suggestions",
  "v1.session.vocabEmpty": "No vocabulary suggestions for this answer",
  "v1.session.rewrite": "Natural rewrite (keeps your meaning)",
  "v1.session.rewriteGenerating": "Generating rewrite…",
  "v1.session.degraded": "Answer saved, feedback unavailable",
  "v1.session.degradedRetry": "Retry feedback",
  "v1.session.saved": "Answer saved",
  "v1.session.stageTarget": "Generated for your {band} training target",
  "v1.session.next": "Next question",
  "v1.session.finish": "Finish practice",
  "v1.session.summaryFamiliar.title": "Practice summary",
  "v1.session.summaryFamiliar.desc": "Training feedback only, not an official score. This mode produces no band or diagnostic",
  "v1.session.summaryStandard.title": "Topic training estimate",
  "v1.session.summaryStandard.note": "Training estimate, not an official score",
  "v1.session.summary.basis": "Why this estimate",
  "v1.session.summary.nextFocus": "Next focus",
  "v1.session.summary.answers": "{count} questions completed",
  "v1.session.summary.backHome": "Back to practice home",
  "v1.session.summary.viewHistory": "View history",
  "v1.session.summary.repractice": "Practice again",
  "v1.session.summary.unavailable": "Summary unavailable — try again later",
  "v1.session.summary.generating": "Generating summary…",
  "v1.session.micError": "Microphone unavailable: {message}",
  "v1.session.aria.timer": "{seconds} seconds remaining",
  "v1.session.loadError": "Failed to load practice session",

  // ===== V1 History (FR-010) =====
  "v1.history.title": "Daily practice",
  "v1.history.empty": "No daily practice yet — start speaking from the practice page",
  "v1.history.review": "Review",
  "v1.history.delete": "Delete",
  "v1.history.confirmDelete": "Delete this practice record?",
  "v1.history.status.completed": "Completed",
  "v1.history.status.in_progress": "In progress",
  "v1.history.answers": "{done}/{total} answered",
  "v1.history.reviewTitle": "Practice review",
  "v1.history.estimate": "Training estimate {band}",
  "v1.history.reviewQuestion": "Question {index}",
  "v1.history.reviewSkipped": "Skipped",

  // ===== V1 Diagnostic (FR-009) =====
  "v1.diag.title": "Diagnostic complete",
  "v1.diag.desc": "Training estimate, not an official score",
  "v1.diag.current": "Current level",
  "v1.diag.target": "Final goal",
  "v1.diag.stage": "Current training target",
  "v1.diag.dimensions": "Four dimensions",
  "v1.diag.notAssessed": "Not assessed",
  "v1.diag.notes": "Evidence",
  "v1.diag.stagePlan": "Stage path",
  "v1.diag.startPractice": "Start practicing",
  "v1.diag.viewProgress": "View progress",
};

const dict: Record<Locale, Dict> = { zh, en };

export function t(
  locale: Locale,
  key: string,
  vars?: Record<string, string | number>,
): string {
  const template = dict[locale]?.[key] ?? dict.en[key] ?? key;
  if (!vars) {
    return template;
  }
  return template.replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value !== undefined ? String(value) : match;
  });
}
