// 中英双语字典 — 所有静态 UI 文案都走这里。
// 题目/逐字稿/范文保持英文（雅思考试是英文），只有界面 chrome 双语化。
// 键名用点分路径（如 "nav.bank"），命名按功能域分组。

export type Locale = "zh" | "en";

export const LOCALES: Locale[] = ["zh", "en"];

type Dict = Record<string, string>;

const zh: Dict = {
  // ===== 品牌 =====
  "brand.name": "雅思口语训练",
  "brand.tagline": "真题训练 · 答题框架 · 预测背诵",
  "brand.full": "雅思口语训练系统",

  // ===== 导航 =====
  "nav.bank": "题库",
  "nav.library": "素材本",
  "nav.settings": "设置",
  "nav.signIn": "登录",
  "nav.signOut": "退出",
  "nav.signUp": "注册",

  // ===== 落地页 =====
  "home.hero.title": "练出你的雅思口语答题框架",
  "home.hero.subtitle":
    "基于历年真题开口练习，AI 自动提炼答题框架；临考用预测题按框架背诵，把会写变成能说。",
  "home.cta.start": "开始练习",
  "home.cta.browse": "浏览题库",
  "home.step1.title": "① 真题训练",
  "home.step1.desc": "从历年真题题库选一道题，开口回答。实时识别并标记填充词、犹豫词、低分词。",
  "home.step2.title": "② 提炼框架",
  "home.step2.desc": "AI 基于你的回答自动提炼答题框架：结构、要点、高分表达，存入个人素材本。",
  "home.step3.title": "③ 预测背诵",
  "home.step3.desc": "临考切换到预测题库，用框架关键词提示卡背诵实践，考前内化输出。",

  // ===== 认证 =====
  "auth.signIn.title": "登录雅思口语训练",
  "auth.signUp.title": "创建账户",
  "auth.tab.signIn": "登录",
  "auth.tab.signUp": "注册",
  "auth.method.password": "密码登录",
  "auth.method.emailCode": "邮箱验证码",
  "auth.field.identifier": "邮箱或用户名",
  "auth.field.password": "密码",
  "auth.field.email": "邮箱",
  "auth.field.name": "你的名字",
  "auth.field.username": "用户名",
  "auth.field.code": "六位验证码",
  "auth.remember": "在此设备保持登录",
  "auth.submit.signIn": "登录",
  "auth.submit.signInBusy": "登录中…",
  "auth.submit.create": "创建账户",
  "auth.submit.createBusy": "创建中…",
  "auth.submit.sendCode": "发送登录验证码",
  "auth.submit.sendingCode": "发送中…",
  "auth.submit.verify": "验证并登录",
  "auth.submit.verifying": "验证中…",
  "auth.submit.verifyAndContinue": "验证并继续",
  "auth.codeSentTo": "验证码已发送至",
  "auth.useAnotherEmail": "使用其他邮箱",
  "auth.verifyEmail.title": "验证你的邮箱",
  "auth.resendCode": "重新发送验证码",
  "auth.create.subtitle": "注册一个账户，保存你的框架与练习记录",
  "auth.passwordHelp": "使用 8–128 位字符",
  "auth.otp.notice": "如果该邮箱有账户，六位验证码已发送",
  "auth.otp.notice2": "六位验证码已发送至你的邮箱",
  "auth.welcome": "欢迎使用雅思口语训练系统",

  // ===== 题库 =====
  "bank.title": "雅思口语题库",
  "bank.subtitle": "选择一道题开始练习",
  "bank.part1": "Part 1",
  "bank.part2": "Part 2",
  "bank.part3": "Part 3",
  "bank.allParts": "全部",
  "bank.real": "历年真题",
  "bank.predicted": "预测题",
  "bank.year.all": "全部年份",
  "bank.topic.all": "全部话题",
  "bank.practice": "开始练习",
  "bank.recite": "背记",
  "bank.modelAnswer": "看范文",
  "bank.needSignIn": "登录后可练习",
  "bank.empty": "该筛选条件下暂无题目",

  // ===== 练习 =====
  "practice.title": "口语练习",
  "practice.prepTime": "准备时间",
  "practice.prepDesc": "1 分钟准备你的回答",
  "practice.start": "开始录制",
  "practice.pause": "暂停",
  "practice.resume": "继续",
  "practice.stop": "结束",
  "practice.generateReport": "生成报告",
  "practice.speakHint": "点击开始，说出你的回答",
  "practice.recording": "正在录音…",
  "practice.paused": "已暂停",
  "practice.stat.fillers": "填充词",
  "practice.stat.hedges": "犹豫词",
  "practice.stat.vague": "低分词",
  "practice.stat.chinglish": "中式英语",
  "practice.stat.density": "表达密度",
  "practice.stat.words": "词数",
  "practice.coach": "实时教练",
  "practice.coachEmpty": "AI 教练提示将显示在这里",
  "practice.framework": "答题框架",
  "practice.frameworkEmpty": "练习结束后可提取框架",
  "practice.saveFramework": "保存框架",
  "practice.report.title": "练习报告",
  "practice.report.generating": "正在生成报告…",
  "practice.report.failed": "报告生成失败，请稍后重试",
  "practice.report.close": "关闭",
  "practice.micUnsupported": "您的浏览器不支持语音识别，请使用 Chrome 或 Edge",
  "practice.micPermission": "无法访问麦克风，请检查浏览器权限设置",
  "practice.exit": "退出练习",

  // ===== 素材本 =====
  "library.title": "我的素材本",
  "library.subtitle": "按话题整理的答题框架",
  "library.empty": "还没有框架，先去题库练一道题吧",
  "library.edit": "编辑",
  "library.export": "导出",
  "library.delete": "删除",
  "library.deleteConfirm": "确定删除这个框架吗？",
  "library.structure": "结构",
  "library.keyPoints": "要点",
  "library.expressions": "高分表达",
  "library.intro": "导语",
  "library.save": "保存",
  "library.cancel": "取消",

  // ===== 背记 =====
  "recite.title": "背诵实践",
  "recite.hint": "看着关键词提示，自然地说出你的回答",
  "recite.reveal": "显示提示词",
  "recite.hide": "隐藏提示词",
  "recite.compare": "对比范文",

  // ===== 设置 =====
  "settings.title": "设置",
  "settings.language": "界面语言",
  "settings.language.zh": "中文",
  "settings.language.en": "English",
  "settings.asr": "语音识别语言",
  "settings.account": "账户",
  "settings.account.email": "邮箱",
  "settings.account.username": "用户名",
  "settings.signOut": "退出登录",
  "settings.llm": "AI 服务",
  "settings.llm.configured": "已配置",
  "settings.llm.notConfigured": "未配置",
  "settings.llm.provider": "服务商",

  // ===== 通用 =====
  "common.loading": "加载中…",
  "common.back": "返回",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.confirm": "确认",
  "common.error": "出错了",
  "common.retry": "重试",
  "common.minutes": "分钟",
  "common.seconds": "秒",
  "common.word": "词",
  "common.words": "词",
  "common.mode.train": "训练",
  "common.mode.recite": "背记",
};

const en: Dict = {
  "brand.name": "IELTS Speaking",
  "brand.tagline": "Real questions · Frameworks · Predicted reciting",
  "brand.full": "IELTS Speaking Trainer",

  "nav.bank": "Question Bank",
  "nav.library": "My Frameworks",
  "nav.settings": "Settings",
  "nav.signIn": "Sign in",
  "nav.signOut": "Sign out",
  "nav.signUp": "Sign up",

  "home.hero.title": "Build your IELTS speaking framework",
  "home.hero.subtitle":
    "Practice on real past-exam questions, let AI extract a reusable answer framework, then recite on predicted questions before your test.",
  "home.cta.start": "Start practicing",
  "home.cta.browse": "Browse questions",
  "home.step1.title": "① Train on real questions",
  "home.step1.desc": "Pick a question from the past-exam bank and answer it out loud. Fillers, hesitations and low-band words are marked in real time.",
  "home.step2.title": "② Extract a framework",
  "home.step2.desc": "AI distills your answer into a framework: structure, key points and high-band expressions, saved to your library.",
  "home.step3.title": "③ Recite on predicted questions",
  "home.step3.desc": "Switch to the predicted bank before your test and recite from keyword cue cards to internalize your frameworks.",

  "auth.signIn.title": "Sign in to IELTS Speaking",
  "auth.signUp.title": "Create your account",
  "auth.tab.signIn": "Sign in",
  "auth.tab.signUp": "Sign up",
  "auth.method.password": "Password",
  "auth.method.emailCode": "Email code",
  "auth.field.identifier": "Email or username",
  "auth.field.password": "Password",
  "auth.field.email": "Email",
  "auth.field.name": "Your name",
  "auth.field.username": "Username",
  "auth.field.code": "Six-digit code",
  "auth.remember": "Keep me signed in on this device",
  "auth.submit.signIn": "Sign in",
  "auth.submit.signInBusy": "Signing in…",
  "auth.submit.create": "Create account",
  "auth.submit.createBusy": "Creating…",
  "auth.submit.sendCode": "Send sign-in code",
  "auth.submit.sendingCode": "Sending…",
  "auth.submit.verify": "Verify and sign in",
  "auth.submit.verifying": "Verifying…",
  "auth.submit.verifyAndContinue": "Verify and continue",
  "auth.codeSentTo": "Code sent to",
  "auth.useAnotherEmail": "Use another email",
  "auth.verifyEmail.title": "Verify your email",
  "auth.resendCode": "Resend verification code",
  "auth.create.subtitle": "Create an account to save your frameworks and practice history",
  "auth.passwordHelp": "Use 8–128 characters",
  "auth.otp.notice": "If this email belongs to an account, a six-digit code is on its way.",
  "auth.otp.notice2": "A six-digit verification code is on its way.",
  "auth.welcome": "Welcome to IELTS Speaking Trainer",

  "bank.title": "IELTS Speaking Question Bank",
  "bank.subtitle": "Pick a question to start practicing",
  "bank.part1": "Part 1",
  "bank.part2": "Part 2",
  "bank.part3": "Part 3",
  "bank.allParts": "All",
  "bank.real": "Real questions",
  "bank.predicted": "Predicted",
  "bank.year.all": "All years",
  "bank.topic.all": "All topics",
  "bank.practice": "Start practice",
  "bank.recite": "Recite",
  "bank.modelAnswer": "Model answer",
  "bank.needSignIn": "Sign in to practice",
  "bank.empty": "No questions match this filter",

  "practice.title": "Speaking practice",
  "practice.prepTime": "Preparation",
  "practice.prepDesc": "Prepare your answer for 1 minute",
  "practice.start": "Start recording",
  "practice.pause": "Pause",
  "practice.resume": "Resume",
  "practice.stop": "Stop",
  "practice.generateReport": "Generate report",
  "practice.speakHint": "Click start and speak your answer",
  "practice.recording": "Recording…",
  "practice.paused": "Paused",
  "practice.stat.fillers": "Fillers",
  "practice.stat.hedges": "Hesitations",
  "practice.stat.vague": "Low-band words",
  "practice.stat.chinglish": "Chinglish",
  "practice.stat.density": "Density",
  "practice.stat.words": "Words",
  "practice.coach": "AI Coach",
  "practice.coachEmpty": "AI coaching tips will appear here",
  "practice.framework": "Answer framework",
  "practice.frameworkEmpty": "Extract a framework after you finish",
  "practice.saveFramework": "Save framework",
  "practice.report.title": "Practice report",
  "practice.report.generating": "Generating report…",
  "practice.report.failed": "Failed to generate report. Try again.",
  "practice.report.close": "Close",
  "practice.micUnsupported": "Your browser does not support speech recognition. Use Chrome or Edge.",
  "practice.micPermission": "Cannot access the microphone. Check your browser permissions.",
  "practice.exit": "Exit practice",

  "library.title": "My Frameworks",
  "library.subtitle": "Answer frameworks organized by topic",
  "library.empty": "No frameworks yet. Practice a question to build one.",
  "library.edit": "Edit",
  "library.export": "Export",
  "library.delete": "Delete",
  "library.deleteConfirm": "Delete this framework?",
  "library.structure": "Structure",
  "library.keyPoints": "Key points",
  "library.expressions": "High-band expressions",
  "library.intro": "Intro",
  "library.save": "Save",
  "library.cancel": "Cancel",

  "recite.title": "Recite practice",
  "recite.hint": "Look at the keyword cues and speak your answer naturally",
  "recite.reveal": "Reveal cues",
  "recite.hide": "Hide cues",
  "recite.compare": "Compare with model answer",

  "settings.title": "Settings",
  "settings.language": "Interface language",
  "settings.language.zh": "中文",
  "settings.language.en": "English",
  "settings.asr": "Speech recognition language",
  "settings.account": "Account",
  "settings.account.email": "Email",
  "settings.account.username": "Username",
  "settings.signOut": "Sign out",
  "settings.llm": "AI service",
  "settings.llm.configured": "Configured",
  "settings.llm.notConfigured": "Not configured",
  "settings.llm.provider": "Provider",

  "common.loading": "Loading…",
  "common.back": "Back",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.error": "Something went wrong",
  "common.retry": "Retry",
  "common.minutes": "min",
  "common.seconds": "s",
  "common.word": "word",
  "common.words": "words",
  "common.mode.train": "Train",
  "common.mode.recite": "Recite",
};

const dict: Record<Locale, Dict> = { zh, en };

export function t(locale: Locale, key: string): string {
  return dict[locale]?.[key] ?? dict.en[key] ?? key;
}
